### ISSUE TITLE
[BUG] RuntimeError: CUDA error: invalid device ordinal. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by whysirier** [QwenLM/Qwen-VL#217]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1. 官方的finetune.py中device_map默认是None
2. 在Qwen-7B中执行 bash finetune/finetune_qlora_ds.sh能正常训练，并有结果输出
3. 在Qwen-VL中，Int4版本而非In4版本，均报以下错误：
![Qwen-VL](https://github.com/QwenLM/Qwen-VL/assets/142364107/c862df79-642e-4e3f-a9f1-0e4c410b858f)

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.32.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.2
- 显卡: 2 * V100
```

**Comment by whysirier** [comment]
VL的Int4版本或非In4版本，均报以上错误，不知道是不是transformer等包不兼容的问题

**Comment by whysirier** [comment]
默认是8张卡，将sh中的GPUS_PER_NODE = 8 改成GPUS_PER_NODE=$(python -c 'import torch; print(torch.cuda.device_count())')就好了
